### Objectives
* Challenges with current code
* Understanding Pipeline
* Solving Problems using Pipeline
* Challenges with Pipeline
* Solving hetrogenous data problem with ColumnTransformer

<hr>

### Challenges with current code
* Dev have to do manually the preprocessing followed by putting the data in the estimators

In [23]:
from sklearn.datasets import load_digits

In [24]:
dataset = load_digits()

In [25]:
dataset.data.shape

(1797, 64)

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target)

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
ss = StandardScaler()

In [39]:
trainX_tf = ss.fit_transform(X_train)

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
classifier_rf = RandomForestClassifier()

In [42]:
classifier_rf.fit(trainX_tf, y_train)

RandomForestClassifier()

In [43]:
#This is incorrect, testX isn't tranformed
classifier_rf.predict(X_test)

array([8, 1, 1, 8, 6, 6, 1, 1, 8, 8, 4, 1, 1, 8, 1, 0, 8, 1, 1, 0, 8, 6,
       2, 9, 8, 1, 9, 0, 6, 9, 6, 8, 8, 8, 0, 8, 1, 8, 8, 8, 8, 1, 8, 1,
       8, 6, 1, 8, 0, 8, 9, 1, 8, 8, 8, 1, 6, 8, 0, 1, 1, 0, 8, 1, 9, 1,
       0, 1, 1, 1, 9, 8, 8, 6, 1, 1, 1, 1, 0, 8, 8, 1, 1, 9, 8, 1, 9, 0,
       8, 9, 9, 9, 0, 2, 9, 1, 1, 1, 8, 1, 1, 1, 0, 8, 0, 1, 9, 9, 8, 8,
       9, 9, 8, 8, 8, 9, 8, 8, 9, 1, 9, 1, 8, 8, 1, 0, 1, 1, 8, 8, 8, 8,
       4, 8, 8, 0, 0, 8, 1, 1, 6, 1, 8, 8, 8, 0, 1, 8, 1, 0, 9, 8, 0, 8,
       8, 9, 1, 9, 1, 1, 1, 1, 8, 0, 1, 8, 8, 8, 1, 0, 6, 6, 1, 1, 8, 1,
       8, 8, 1, 0, 1, 1, 2, 1, 1, 1, 6, 0, 0, 9, 8, 8, 0, 1, 1, 8, 1, 9,
       8, 8, 1, 9, 1, 1, 8, 1, 9, 9, 0, 9, 1, 8, 8, 8, 8, 8, 1, 1, 1, 1,
       0, 0, 1, 0, 8, 0, 1, 8, 8, 0, 6, 9, 8, 8, 9, 6, 9, 9, 8, 6, 1, 4,
       1, 0, 1, 2, 1, 1, 1, 8, 1, 9, 8, 8, 8, 8, 1, 8, 0, 1, 8, 1, 8, 8,
       1, 8, 1, 9, 0, 1, 8, 0, 0, 8, 8, 1, 8, 1, 1, 4, 8, 8, 1, 8, 1, 4,
       9, 8, 8, 9, 9, 8, 1, 8, 1, 8, 8, 0, 1, 9, 1,

In [44]:
testX_tf = ss.transform(X_test)

In [45]:
#Difference can be seen in prediction from above
classifier_rf.predict(testX_tf)

array([2, 1, 1, 4, 6, 6, 9, 7, 8, 3, 4, 7, 2, 3, 1, 4, 2, 1, 7, 0, 7, 6,
       2, 9, 2, 2, 9, 0, 6, 5, 6, 6, 2, 8, 4, 4, 1, 6, 8, 8, 8, 7, 5, 1,
       6, 6, 8, 6, 4, 3, 5, 7, 3, 7, 1, 1, 6, 1, 0, 8, 1, 0, 8, 4, 8, 4,
       0, 4, 5, 1, 5, 7, 6, 6, 8, 8, 1, 4, 4, 6, 7, 4, 3, 9, 3, 8, 3, 0,
       3, 3, 3, 3, 0, 2, 9, 7, 1, 7, 8, 4, 1, 8, 0, 2, 4, 7, 9, 3, 3, 2,
       3, 9, 9, 7, 1, 9, 2, 9, 3, 6, 5, 3, 0, 7, 4, 4, 4, 4, 2, 5, 5, 3,
       4, 2, 7, 0, 0, 5, 5, 6, 6, 1, 1, 9, 6, 4, 8, 8, 4, 0, 5, 2, 7, 2,
       3, 9, 5, 3, 8, 1, 6, 5, 2, 0, 9, 6, 8, 8, 1, 4, 6, 6, 1, 1, 3, 1,
       2, 6, 2, 0, 1, 1, 2, 3, 8, 3, 6, 0, 0, 9, 1, 1, 0, 6, 6, 5, 4, 9,
       3, 8, 3, 3, 8, 1, 8, 4, 9, 9, 0, 9, 0, 2, 2, 9, 3, 9, 8, 8, 4, 1,
       0, 0, 6, 4, 3, 0, 6, 8, 8, 4, 6, 9, 3, 2, 9, 6, 9, 7, 2, 6, 7, 4,
       1, 4, 1, 2, 1, 8, 6, 7, 5, 5, 8, 7, 3, 6, 1, 6, 7, 1, 6, 1, 3, 8,
       4, 2, 9, 9, 0, 5, 5, 4, 0, 7, 8, 7, 1, 0, 4, 4, 6, 7, 5, 8, 4, 4,
       9, 3, 3, 9, 9, 8, 8, 8, 2, 2, 8, 0, 1, 2, 1,

### Challenges
* Different features need differnt preprocessing
* It's very cumbersome to do things the current way
* We have to preserve manually all the preprocessors used

### Pipeline
* It connects preprocessor & estimators & thus removes the need to store them manually
* In same line, the code will perform all necessary preprocessing steps, fitting the model or calling predict.
* Easy for others to understand flow
* Can enforce order in which transformation need to happen

In [46]:
from sklearn.pipeline import make_pipeline

In [47]:
digit_pipeline = make_pipeline(StandardScaler(), RandomForestClassifier())

In [48]:
digit_pipeline.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestclassifier', RandomForestClassifier())])

In [94]:
y_pred = digit_pipeline.predict(X_test)

In [95]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8888888888888888

In [50]:
#Feature importance: assigning a score to input features based on their usefulness in predicting the target variable
digit_pipeline.steps[1][1].feature_importances_

array([0.00000000e+00, 2.46077769e-03, 2.13059145e-02, 1.08566759e-02,
       9.56557049e-03, 2.17057235e-02, 7.23178930e-03, 8.29459303e-04,
       1.50834140e-05, 1.29031968e-02, 2.68956343e-02, 7.62118856e-03,
       1.35133751e-02, 2.83827148e-02, 5.11118499e-03, 4.84355497e-04,
       2.09312651e-05, 6.79529398e-03, 1.92449643e-02, 2.21976694e-02,
       2.97058107e-02, 5.54491603e-02, 8.43355284e-03, 2.95639716e-04,
       5.05047414e-05, 1.27543496e-02, 4.48833603e-02, 2.29610665e-02,
       3.46062642e-02, 2.54385126e-02, 3.40863397e-02, 1.63826471e-05,
       0.00000000e+00, 2.65928324e-02, 2.51825922e-02, 1.96636166e-02,
       3.80834579e-02, 2.16252406e-02, 2.35551152e-02, 0.00000000e+00,
       2.80168676e-05, 1.01590821e-02, 3.82182630e-02, 4.03858633e-02,
       2.14827606e-02, 1.91752770e-02, 1.85481322e-02, 3.43112346e-05,
       2.14660464e-05, 3.02546124e-03, 1.59820883e-02, 2.07988302e-02,
       1.34202851e-02, 2.63070239e-02, 2.38844124e-02, 1.68153982e-03,
      

### Connecting Pipeline with Hyper-parameter Tuning
* We could determine the best combination of hyper-parameters for preprocessor & estimator

In [51]:
from sklearn.feature_selection import SelectKBest, f_classif

* f_classif (ANOVA: Analysis of Variance) returns a p-value for each feature
* first 10 features with the lowest p-values
* The p-value is the probability that the null hypothesis is true. That's it.
* null hypothesis: which states that there is no change in the revenue as a result of the new marketing campaign, is true. If the value of the p-value is 0.25, then there is a 25% probability that there is no real increase or decrease in revenue as a result of the new marketing campaign. If the value of the p-value is 0.04 then there is a 4% probability that there is no real increase or decrease in revenue as a result of the new marketing campaign. As you can surmise, the lower the p-value, the more confident we are that the alternate hypothesis is true, which, in this case, means that the new marketing campaign causes an increase or decrease in revenue.

In [101]:

digit_pipeline = make_pipeline(StandardScaler(), SelectKBest(k=10, score_func=f_classif), RandomForestClassifier(n_estimators=100))

In [102]:
digit_pipeline

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('selectkbest', SelectKBest()),
                ('randomforestclassifier', RandomForestClassifier())])

In [103]:
digit_pipeline.fit(X_train, y_train)

C:\Users\RISHBANS\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 0 32 39] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx,
C:\Users\RISHBANS\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('selectkbest', SelectKBest()),
                ('randomforestclassifier', RandomForestClassifier())])

In [104]:
y_pred = digit_pipeline.predict(X_test)

In [105]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8955555555555555

In [54]:
from sklearn.model_selection import GridSearchCV

In [32]:
#params = {'selectkbest__k':[20,30,40], 'randomforestclassifier__n_estimators':[100,200]}

In [78]:
params = {'selectkbest__k':[50,55,60, 90], 'randomforestclassifier__n_estimators':[200,250]}

In [79]:
gs = GridSearchCV(digit_pipeline, param_grid=params, cv=5, n_jobs=4)

In [80]:
gs.fit(X_train, y_train)

C:\Users\RISHBANS\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 0 32 39] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx,
C:\Users\RISHBANS\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('selectkbest', SelectKBest()),
                                       ('randomforestclassifier',
                                        RandomForestClassifier())]),
             n_jobs=4,
             param_grid={'randomforestclassifier__n_estimators': [200, 250],
                         'selectkbest__k': [50, 55, 60, 90]})

In [81]:
gs.best_params_

{'randomforestclassifier__n_estimators': 250, 'selectkbest__k': 55}

In [82]:
gs.best_score_

0.9740162467300013

In [48]:
gs.predict(testX[:2])

array([2, 1])

In [49]:
gs.best_estimator_

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('selectkbest',
                 SelectKBest(k=55,
                             score_func=<function f_classif at 0x7efd7e3d3f28>)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=200, n_jobs=None,
                                        oob_score=

### Column Transformer for dealing with hetrogenous data
* Regular Pipeline intends to do same processing for all the columns
* This doesn't work for hetrogenous data

<img src="https://github.com/edyoda/Data-Scientist-program/blob/master/Assignment/images/ColumnTranformer.png?raw=true">

In [51]:
import pandas as pd

In [52]:
hr_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/HR_comma_sep.csv.txt')

In [54]:
hr_data.rename(columns={'sales':'dept'},inplace=True)

In [55]:
hr_data.sample(5)

satisfaction_level  last_evaluation  number_project  \
309                  0.10             0.94               6   
12579                0.39             0.55               2   
8683                 0.23             0.96               4   
12495                0.82             0.99               4   
4451                 0.87             0.68               5   

       average_montly_hours  time_spend_company  Work_accident  left  \
309                     285                   4              0     1   
12579                   159                   3              0     1   
8683                    213                   4              0     0   
12495                   263                   6              0     1   
4451                    187                   3              0     0   

       promotion_last_5years       dept  salary  
309                        0    support  medium  
12579                      0  technical    high  
8683                       0  technical  medium  
12495                      0  technical  medium  
4451                       0      sales     low

In [56]:
feature_data = hr_data.drop(columns=['left'])

In [57]:
target_data = hr_data.left

* Differnt columns needs differnt preprocessing

In [60]:
cat_data = feature_data.select_dtypes(include=['object'])

In [62]:
#satisfaction_level & last_evaluation don't need preprocessing
#number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years need MinMaxScaler
#dept & Salary need OrdinalEncoder
feature_data.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
promotion_last_5years      int64
dept                      object
salary                    object
dtype: object

In [63]:
float_data = feature_data.select_dtypes(include=['float'])

In [65]:
float_data[:4]

satisfaction_level  last_evaluation
0                0.38             0.53
1                0.80             0.86
2                0.11             0.88
3                0.72             0.87

In [66]:
int_data = feature_data.select_dtypes(include=['int'])

In [113]:
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer

In [69]:
#cat_pipeline = make_pipeline(SimpleImputer(),OrdinalEncoder())
#SimpleImpter is for handling missing data in pipeline

cat_pipeline = make_pipeline(OrdinalEncoder())

In [89]:
int_pipeline = make_pipeline(MinMaxScaler(), SelectKBest(k=3,score_func=f_classif))

In [90]:
from sklearn.compose import make_column_transformer

In [91]:
preprocessor = make_column_transformer(
              (cat_pipeline,cat_data.columns),
              (int_pipeline,int_data.columns),
              remainder='passthrough'
)

In [92]:
pipeline = make_pipeline(preprocessor, RandomForestClassifier())

In [93]:
trainX,testX, trainY, testY = train_test_split(feature_data, target_data)

In [94]:
trainX[:2]

satisfaction_level  last_evaluation  number_project  \
14443                0.11             0.83               6   
12791                0.82             0.49               4   

       average_montly_hours  time_spend_company  Work_accident  \
14443                   244                   4              0   
12791                   276                   4              0   

       promotion_last_5years        dept salary  
14443                      0  accounting    low  
12791                      0     support    low

In [95]:
pipeline.fit(trainX, trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('pipeline-1',
                                                  Pipeline(memory=None,
                                                           steps=[('ordinalencoder',
                                                                   OrdinalEncoder(categories='auto',
                                                                                  dtype=<class 'numpy.float64'>))],
                                                           verbose=False),
                                                  Index(['dept', 'salary'], dtype='object')),
                                                 ('pipe...
                 RandomForestClassifier(bootstrap=True, class_weight=None,
        

In [96]:
pipeline.predict(testX[:2])

array([0, 0])

In [97]:
pipeline.score(testX,testY)

0.9866666666666667

In [100]:
pipeline.steps[0][1].transformers

[('pipeline-1', Pipeline(memory=None,
           steps=[('ordinalencoder',
                   OrdinalEncoder(categories='auto',
                                  dtype=<class 'numpy.float64'>))],
           verbose=False), Index(['dept', 'salary'], dtype='object')),
 ('pipeline-2', Pipeline(memory=None,
           steps=[('minmaxscaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                  ('selectkbest',
                   SelectKBest(k=3,
                               score_func=<function f_classif at 0x7efd7e3d3f28>))],
           verbose=False), Index(['number_project', 'average_montly_hours', 'time_spend_company',
         'Work_accident', 'promotion_last_5years'],
        dtype='object'))]

In [101]:
params = {'columntransformer__pipeline-2__selectkbest__k':[2,3]}

In [102]:
gs = GridSearchCV(pipeline, param_grid=params, n_jobs=4, cv=5)

In [103]:
gs.fit(trainX,trainY)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('columntransformer',
                                        ColumnTransformer(n_jobs=None,
                                                          remainder='passthrough',
                                                          sparse_threshold=0.3,
                                                          transformer_weights=None,
                                                          transformers=[('pipeline-1',
                                                                         Pipeline(memory=None,
                                                                                  steps=[('ordinalencoder',
                                                                                          OrdinalEncoder(categories='auto',
                                                                                                         dtype

In [104]:
gs.best_params_

{'columntransformer__pipeline-2__selectkbest__k': 3}

In [105]:
gs.best_score_

0.9847986487687794

### Disadvantages of Pipeline
* Doesn't support Online Learning
* Online Learning will be discussed later

### Dealing with imbalanced data in pipeline
* Use imblearn make_pipeline rather than scikit make_pipeline as RandomOverSampler is not supported in scikit

In [106]:
target_data.value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [109]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.pipeline import make_pipeline

In [110]:
#This make_pipeline is not scikit pipeline but imblearn pipeline which support Oversampler as part of pipeline
pipeline = make_pipeline(preprocessor, RandomOverSampler(), RandomForestClassifier())

In [111]:
pipeline.fit(trainX, trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('pipeline-1',
                                                  Pipeline(memory=None,
                                                           steps=[('ordinalencoder',
                                                                   OrdinalEncoder(categories='auto',
                                                                                  dtype=<class 'numpy.float64'>))],
                                                           verbose=False),
                                                  Index(['dept', 'salary'], dtype='object')),
                                                 ('pipe...
                 RandomForestClassifier(bootstrap=True, class_weight=None,
        

In [112]:
pipeline.score(testX,testY)

0.9864